repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.9.1
          - "@typescript-eslint/parser@6.13.0"
          - "@typescript-eslint/eslint-plugin@6.13.0"
        args: ["--ext", ".ts,.tsx"]
        files: ^(frontend/)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(ts|tsx|js|jsx|json|yaml|yml|md)$
